### ISSUE TITLE
Injector Error

### ISSUE THREAD

**Issue by jessejburton** [angular-slider/angularjs-slider#636]
I have installed the directive as outlined in the instructions but I get this message:

Error: $injector:modulerr
Module Error
Failed to instantiate module SSCY due to:
Error: [ng:areq] http://errors.angularjs.org/1.6.9/ng/areq?p0=fn&p1=not%20...
    at http://localhost/SSCY/js/vendor/angular.js:7:76
    at hb (http://localhost/SSCY/js/vendor/angular.js:24:158)
    at sb (http://localhost/SSCY/js/vendor/angular.js:24:245)
    at Function.gb.$$annotate (http://localhost/SSCY/js/vendor/angular.js:209:361)
    at e (http://localhost/SSCY/js/vendor/angular.js:43:412)
    at Object.invoke (http://localhost/SSCY/js/vendor/angular.js:44:124)
    at d (http://localhost/SSCY/js/vendor/angular.js:42:279)
    at http://localhost/SSCY/js/vendor/angular.js:42:418
    at r (http://localhost/SSCY/js/vendor/angular.js:8:7)
    at g (http://localhost/SSCY/js/vendor/angular.js:42:180

The js file is loading correctly from the CDN, here is my app module line:

var sscy = angular.module('SSCY',['720kb.datepicker'],['rzModule']);

It works without the 'rzModule' added, this is the line it breaks on but I am not sure how to debug as the error message doesn't seem to be very helpful.

Thanks!

**Comment by jessejburton** [comment]
Figured it out, had an error in my app module line

var sscy = angular.module('SSCY',['720kb.datepicker', 'rzModule']);
